---

# be faster in CI
nginx_dhparam_bits: 512

# ignore errors on firewalld (we have no firewalld in CI )
nginx_firewalld_ignore_errors: false

nginx_sites:
  - name: ci-test
    root: /opt/nginx/ci-test-root
    with_ssl: false
    without_ssl: true
    is_default: true
